
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import { ToastContainer } from "react-toastify";
import ToastProvider from "@/components/ToastProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SumFlood",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo.png", // İkonun yolu
    shortcut: "/favicon.ico", // Kısayol ikonu
    apple: "/apple-touch-icon.png", // (Varsa) Apple cihazları için ikon
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-full`}>
       
        <StoreProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </StoreProvider>

     
       
      </body>
    </html>
  );
}
